const fs = require('fs');
const path = require('path');

const MEDIA_PACK_DIR = __dirname;
const PROJECT_ROOT = path.resolve(MEDIA_PACK_DIR, '..');
const DIST_DIR = path.join(PROJECT_ROOT, 'dist');

// Create dist directory if it doesn't exist
if (!fs.existsSync(DIST_DIR)) {
  fs.mkdirSync(DIST_DIR, { recursive: true });
}

console.log('Building Promo Pack for GitHub Pages...');

// 1. Copy mcp_benchmark_results.js
const resultsSrc = path.join(PROJECT_ROOT, 'scratch', 'mcp_benchmark_results.js');
const resultsDest = path.join(DIST_DIR, 'mcp_benchmark_results.js');
if (fs.existsSync(resultsSrc)) {
  fs.copyFileSync(resultsSrc, resultsDest);
  console.log('✅ Copied mcp_benchmark_results.js');
} else {
  console.error('❌ Could not find scratch/mcp_benchmark_results.js');
}

// 2. Copy graph-renderer.js
const rendererSrc = path.join(MEDIA_PACK_DIR, 'graph-renderer.js');
const rendererDest = path.join(DIST_DIR, 'graph-renderer.js');
if (fs.existsSync(rendererSrc)) {
  fs.copyFileSync(rendererSrc, rendererDest);
  console.log('✅ Copied graph-renderer.js');
} else {
  console.error('❌ Could not find media_pack/graph-renderer.js');
}

// 3. Process and Copy HTML
const htmlSrc = path.join(MEDIA_PACK_DIR, 'mcp_promo_pack.html');
const htmlDest = path.join(DIST_DIR, 'index.html');

if (fs.existsSync(htmlSrc)) {
  let htmlContent = fs.readFileSync(htmlSrc, 'utf8');
  
  // Replace the relative script path to point to the local directory
  htmlContent = htmlContent.replace(
    '<script src="../scratch/mcp_benchmark_results.js"></script>',
    '<script src="./mcp_benchmark_results.js"></script>'
  );

  fs.writeFileSync(htmlDest, htmlContent);
  console.log('✅ Processed and copied mcp_promo_pack.html to index.html');
} else {
  console.error('❌ Could not find media_pack/mcp_promo_pack.html');
}

// 4. Copy token audit data shim (window.tokenAuditData) — generated by
//    mcp-server/run_benchmark_v2.js into scratch/.
const auditSrc = path.join(PROJECT_ROOT, 'scratch', 'token_audit_v2.js');
const auditDest = path.join(DIST_DIR, 'token_audit_v2.js');
if (fs.existsSync(auditSrc)) {
  fs.copyFileSync(auditSrc, auditDest);
  console.log('✅ Copied token_audit_v2.js');
} else {
  console.warn('⚠️  scratch/token_audit_v2.js not found — run mcp-server/run_benchmark_v2.js to generate it');
}

const auditGeminiSrc = path.join(PROJECT_ROOT, 'scratch', 'token_audit_gemini.js');
const auditGeminiDest = path.join(DIST_DIR, 'token_audit_gemini.js');
if (fs.existsSync(auditGeminiSrc)) {
  fs.copyFileSync(auditGeminiSrc, auditGeminiDest);
  console.log('✅ Copied token_audit_gemini.js');
} else {
  console.warn('⚠️  scratch/token_audit_gemini.js not found');
}

// 5. Copy the /review validation page (served at /memo-ray/review).
const reviewSrc = path.join(MEDIA_PACK_DIR, 'review.html');
const reviewDest = path.join(DIST_DIR, 'review.html');
if (fs.existsSync(reviewSrc)) {
  fs.copyFileSync(reviewSrc, reviewDest);
  console.log('✅ Copied review.html');
} else {
  console.error('❌ Could not find media_pack/review.html');
}

const reviewGeminiSrc = path.join(MEDIA_PACK_DIR, 'review-gemini.html');
const reviewGeminiDest = path.join(DIST_DIR, 'review-gemini.html');
if (fs.existsSync(reviewGeminiSrc)) {
  fs.copyFileSync(reviewGeminiSrc, reviewGeminiDest);
  console.log('✅ Copied review-gemini.html');
} else {
  console.error('❌ Could not find media_pack/review-gemini.html');
}

// 6. SEO assets: robots.txt, sitemap.xml, and the social share card.
for (const name of ['robots.txt', 'sitemap.xml']) {
  const src = path.join(MEDIA_PACK_DIR, name);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(DIST_DIR, name));
    console.log(`✅ Copied ${name}`);
  } else {
    console.warn(`⚠️  media_pack/${name} not found`);
  }
}
const cardSrc = path.join(MEDIA_PACK_DIR, 'initial_launch', 'viral_thumbnail_mockup.png');
const cardDest = path.join(DIST_DIR, 'social-card.png');
if (fs.existsSync(cardSrc)) {
  fs.copyFileSync(cardSrc, cardDest);
  console.log('✅ Copied social-card.png');
} else {
  console.warn('⚠️  social card image not found');
}

const dashboardImgSrc = path.join(MEDIA_PACK_DIR, 'memoray_dashboard.png');
const dashboardImgDest = path.join(DIST_DIR, 'memoray_dashboard.png');
if (fs.existsSync(dashboardImgSrc)) {
  fs.copyFileSync(dashboardImgSrc, dashboardImgDest);
  console.log('✅ Copied memoray_dashboard.png');
}

const dashboardVidSrc = path.join(MEDIA_PACK_DIR, 'memoray_dashboard.mp4');
const dashboardVidDest = path.join(DIST_DIR, 'memoray_dashboard.mp4');
if (fs.existsSync(dashboardVidSrc)) {
  fs.copyFileSync(dashboardVidSrc, dashboardVidDest);
  console.log('✅ Copied memoray_dashboard.mp4');
} else {
  console.warn('⚠️  memoray_dashboard.mp4 not found');
}

console.log('Build complete! Ready for GitHub Pages deployment.');
